"""edit_roles

Revision ID: 05219327f2bd
Revises: 8b4146a622da
Create Date: 2024-06-08 22:40:01.933978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05219327f2bd'
down_revision = '8b4146a622da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###
